* Encoding: UTF-8.




* CORRS WITH NON-PAR PROGRAMS FOR  MATRICS DOMAIN BASELINE  VS. GSH/GSSH/GSHGSSG GLUTATHIONE BASELINE.

* MATRICS COMPOSITE.

CORRELATIONS
  /VARIABLES=matricsovcompsitew2 GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=matricsovcompsitew2 GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=matricsovcompsitew2 GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=matricsovcompsitew2 GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=matricsovcompsitew2 GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=matricsovcompsitew2 GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=matricsovcompsitew2 gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=matricsovcompsitew2 gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


* MATRICS SPEED OF PROCESSING.

CORRELATIONS
  /VARIABLES=W2MCCBSpeedofProcessing GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBSpeedofProcessing GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBSpeedofProcessing GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBSpeedofProcessing GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2MCCBSpeedofProcessing GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBSpeedofProcessing GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2MCCBSpeedofProcessing gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBSpeedofProcessing gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS ATTENTION VIGILANCE.

CORRELATIONS
  /VARIABLES=W2MCCBAttentionVigilance GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.



NONPAR CORR
  /VARIABLES=W2MCCBAttentionVigilance GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBAttentionVigilance GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBAttentionVigilance GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBAttentionVigilance GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBAttentionVigilance GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2MCCBAttentionVigilance gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBAttentionVigilance gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS SPATIAL WORKING MEMORY.

CORRELATIONS
  /VARIABLES=W2MCCBWorking GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBWorking GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBWorking GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBWorking GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBWorking GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBWorking GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBWorking gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBWorking gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS VERB LEARNING.

CORRELATIONS
  /VARIABLES=W2MCCBVerbalLearning GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVerbalLearning GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2MCCBVerbalLearning GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVerbalLearning GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2MCCBVerbalLearning GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBVerbalLearning GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBVerbalLearning gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVerbalLearning gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


* MATRICS VISUAL LEARNING.

CORRELATIONS
  /VARIABLES=W2MCCBVisualLearning GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVisualLearning GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2MCCBVisualLearning GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVisualLearning GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBVisualLearning GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVisualLearning GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBVisualLearning gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBVisualLearning gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS REASONING PROB SOLVING.

CORRELATIONS
  /VARIABLES=W2MCCBReasoningandProblem GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBReasoningandProblem GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBReasoningandProblem GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBReasoningandProblem GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBReasoningandProblem GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBReasoningandProblem GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBReasoningandProblem gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBReasoningandProblem gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS SOCIAL COGNITION.

CORRELATIONS
  /VARIABLES=W2MCCBSocialCognition GSH_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBSocialCognition GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBSocialCognition GSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBSocialCognition GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBSocialCognition GSHGSSG_0_uMuL
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=W2MCCBSocialCognition GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2MCCBSocialCognition gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2MCCBSocialCognition gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



