* Encoding: UTF-8.
*-- PROGRAMS FOR PANSS POSITIVE  5FACT VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM 

CORRELATIONS
  /VARIABLES=W2PANSSPos5Factbas GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSPos5Factbas GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSPos5Factbas GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSPos5Factbas GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSPos5Factbas GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSPos5Factbas GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2PANSSPos5Factbas total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSPos5Factbas total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



*-- PROGRAMS FOR   PANSS NEGATIVE  5FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM 

CORRELATIONS
  /VARIABLES=W2PANSSNeg5Fact GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5Fact GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSNeg5Fact GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5Fact GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSNeg5Fact GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5Fact GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2PANSSNeg5Fact total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5Fact total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



*-- PROGRAMS FOR   PANSS EXCIT  5FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM 

CORRELATIONS
  /VARIABLES=W2PANSSExcit5Fact GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSExcit5Fact GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSExcit5Fact GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSExcit5Fact GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSExcit5Fact GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSExcit5Fact GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2PANSSExcit5Fact total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSExcit5Fact total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

*-- PROGRAMS FOR   PANSS DEPRESS  5FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM 

CORRELATIONS
  /VARIABLES=W2PANSSDepress5Fact GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSDepress5Fact GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSDepress5Fact GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSDepress5Fact GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSDepress5Fact GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSDepress5Fact GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2PANSSDepress5Fact total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSDepress5Fact total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


*-- PROGRAMS FOR   PANSS COGNITION  5FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM 

CORRELATIONS
  /VARIABLES=W2PANSSCog5Fact GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5Fact GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSCog5Fact GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5Fact GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSCog5Fact GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5Fact GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSCog5Fact total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5Fact total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


*-- PROGRAMS FOR   PANSS NEGATIVE JD FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM 

CORRELATIONS
  /VARIABLES=W2PANSSNeg5FactJDadd GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5FactJDadd GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSNeg5FactJDadd GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5FactJDadd GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSNeg5FactJDadd GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5FactJDadd GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSNeg5FactJDadd total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSNeg5FactJDadd total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



*-- PROGRAMS FOR   PANSS COGNITIVE JD FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE 

CORRELATIONS
  /VARIABLES=W2PANSSCog5FactJDadd GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5FactJDadd GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSCog5FactJDadd GSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5FactJDadd GSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSCog5FactJDadd GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5FactJDadd GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2PANSSCog5FactJDadd total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSCog5FactJDadd total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.





*-- PROGRAMS FOR  PANSSSUM   VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE 

CORRELATIONS
  /VARIABLES=W2PANSSSUM GSH_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSSUM GSH_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSSUM GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSSUM GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=W2PANSSSUM GSHGSSG_0_uMuL
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSSUM GSHGSSG_0_uMuL
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=W2PANSSSUM total_glutathione_0_uMUl
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=W2PANSSSUM total_glutathione_0_uMUl
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


