* Encoding: UTF-8.
*-- PROGRAMS FOR SULFORAPHANE GROUP LD PANSS POSITIVE 5FACTDIFF VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W12W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSPOSFACW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSPOSFACW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSPOSFACW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSPOSFACW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSPOSFACW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSPOSFACW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=PANNSPOSFACW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSPOSFACW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



*-- PROGRAMS FOR SULFORAPHANE GROUP HD PANSS NEGATIVE 5FACTDIFF  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W24W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSNEGFACW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSNEGFACW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSNEGFACW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=PANNSNEGFACW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



*-- PROGRAMS FOR SULFORAPHANE GROUP HD PANSS EXCIT 5FACTDIFF  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W24W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSEXCITFACW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSEXCITFACW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSEXCITFACW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSEXCITFACW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSEXCITFACW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSEXCITFACW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=PANNSEXCITFACW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSEXCITFACW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

*-- PROGRAMS FOR SULFORAPHANE GROUP HD PANSS DEPRESS 5FACTDIFF  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W24W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSDEPRESSFACW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


*-- PROGRAMS FOR SULFORAPHANE GROUP HD PANSS COGNITION 5FACTDIFF  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W24W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSCOGFACW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSCOGFACW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSCOGFACW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


*-- PROGRAMS FOR SULFORAPHANE GROUP HD PANSS NEGATIVE JD FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W24W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSNEGFACJDaddW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



*-- PROGRAMS FOR SULFORAPHANE GROUP HD PANSS COGNITIVE JD FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK24-BAS W24W2 DIFF

CORRELATIONS
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gsh24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gshggssg24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gluathione24wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANNSCOGFACJDaddW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.





*-- PROGRAMS FOR SULFORAPHANE GROUP LD PANSSSUM FACT  VS. GSH/GSSH/GSHGSSHRATIO/GLUTHATHIONE SERUM WK6-BAS W12W2 DIFF

CORRELATIONS
  /VARIABLES=PANSSSUMW12W2DIFF gsh6wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANSSSUMW12W2DIFF gsh6wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANSSSUMW12W2DIFF gssg6wbdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANSSSUMW12W2DIFF gssg6wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PANSSSUMW12W2DIFF gshgssgw6bdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANSSSUMW12W2DIFF gshgssgw6bdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=PANSSSUMW12W2DIFF gluthione6wkvdiff
  /PRINT=TWOTAIL NOSIG
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=PANSSSUMW12W2DIFF gluthione6wkvdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


