* Encoding: UTF-8.




* CORRS WITH NON-PAR PROGRAMS FOR GRP HD MATRICS COMPOSITE W24W2 DIFF VS. GSH/GSSH/GSHGSSG & GLUTH 24W-B DIFF


CORRELATIONS
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSCOMPOSITEW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


* MATRICS SPEED OF PROCESSING.

CORRELATIONS
  /VARIABLES=MATRICSOPROCW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSOPROCW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSOPROCW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSOPROCW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSOPROCW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSOPROCW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSOPROCW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSOPROCW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS ATTENTION VIGILANCE.

CORRELATIONS
  /VARIABLES=MATRICSATTVIGW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.



NONPAR CORR
  /VARIABLES=MATRICSATTVIGW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSATTVIGW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSATTVIGW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSATTVIGW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSATTVIGW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSATTVIGW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSATTVIGW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS SPATIAL WORKING MEMORY.

CORRELATIONS
  /VARIABLES=MATRICSPATWMW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSPATWMW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSPATWMW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSPATWMW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSPATWMW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSPATWMW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSPATWMW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSPATWMW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS VERB LEARNING.

CORRELATIONS
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVERLEARNW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


* MATRICS VISUAL LEARNING.

CORRELATIONS
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CORRELATIONS
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSVISLEARNW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS REASONING PROB SOLVING.

CORRELATIONS
  /VARIABLES=MATRICSREASONPSW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSREASONPSW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSREASONPSW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSREASONPSW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSREASONPSW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSREASONPSW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSREASONPSW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSREASONPSW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

* MATRICS SOCIAL COGNITION.

CORRELATIONS
  /VARIABLES=MATRICSOCCOGW24W2DIFF gsh24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSOCCOGW24W2DIFF gsh24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSOCCOGW24W2DIFF gssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSOCCOGW24W2DIFF gssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSOCCOGW24W2DIFF gshggssg24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=MATRICSOCCOGW24W2DIFF gshggssg24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MATRICSOCCOGW24W2DIFF gluathione24wbdiff
  /PRINT= TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=MATRICSOCCOGW24W2DIFF gluathione24wbdiff
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



